### PR TITLE
Fix whitespace-in-folder bug. Fixes #173

### LINKED ISSUE #173: Folders view breaks with spaces
When a folder has spaces in its name, the view breaks and reports are no longer accessible.

### PR DESCRIPTION
**Pull request by jonbannister**
Fix bug where folders with whitespace were unable to have their results listed. Fixes #173.

Create unit tests for index.js using Jest.
Small refactor of index.js to use JS standards & apply Prettier.

### CODE REVIEW

File: notebooker/web/static/notebooker/index.js [hunk 1]
```diff
@@ -1,132 +1,133 @@
...
-    } else {
-        currentFolder = ""
+const getCurrentFolder = () => {
+    let currentFolder = "";
+    if (window.location.pathname.startsWith("/folder/")) {
+        currentFolder = window.location.pathname.substring("/folder/".length) + "/";
     }
-    return currentFolder
-}
+    return decodeURI(currentFolder);
```
Comment (jonbannister) [inline notebooker/web/static/notebooker/index.js:6]: This was the main culprit - the current folder had `%20` etc. and so the results were incorrectly being filtered out.

**Review by danyaalm — APPROVED** [review]
